# Generated by Django 3.1.6 on 2021-03-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('login', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('steamid', models.CharField(max_length=300)),
                ('shared_secret', models.CharField(max_length=300)),
                ('steamAPI', models.CharField(max_length=300)),
                ('googleDriveId', models.CharField(max_length=300)),
                ('proxy', models.CharField(max_length=300)),
            ],
        ),
    ]
