# Generated by Django 3.1.6 on 2021-03-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210326_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.CharField(max_length=300)),
                ('time', models.CharField(max_length=50)),
                ('proxy', models.CharField(max_length=300)),
                ('request', models.CharField(max_length=1024)),
                ('response', models.CharField(max_length=1024)),
                ('log_type', models.CharField(max_length=300)),
            ],
        ),
    ]
