# Generated by Django 3.1.6 on 2021-03-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bots_turn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('drive_price', models.CharField(max_length=300)),
                ('d_time', models.CharField(max_length=300)),
                ('steam', models.CharField(max_length=300)),
                ('s_time', models.CharField(max_length=300)),
                ('min_profit', models.CharField(max_length=300)),
                ('min_time', models.CharField(max_length=300)),
                ('max_profit', models.CharField(max_length=300)),
                ('max_time', models.CharField(max_length=300)),
                ('hold_off', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('assedID', models.CharField(max_length=300)),
                ('d_discount', models.CharField(max_length=300)),
            ],
        ),
    ]
