# Generated by Django 3.1.6 on 2021-03-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='assedID',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
