# Generated by Django 3.1.5 on 2021-03-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_steamitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='en_link',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='item',
            name='ru_link',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='item',
            name='d_discount',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='d_time',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='drive_price',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='hold_off',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
