# Generated by Django 3.1.5 on 2021-03-31 01:19

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210330_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamitem',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='d_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 31, 4, 19, 52, 446704)),
        ),
        migrations.AlterField(
            model_name='item',
            name='hold_off',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='logs',
            name='bot',
            field=models.CharField(default='', max_length=300),
        ),
    ]
